"""Self-contained high-fidelity agent graph studio served at ``/graphs``."""

PAGE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agent Graphs · llm-super</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='9' fill='%23111318'/%3E%3Cpath d='M8 19c3-8 13-8 16 0M10 13h12' fill='none' stroke='white' stroke-width='2.2' stroke-linecap='round'/%3E%3C/svg%3E">
<style>
:root {
  color-scheme: light;
  --bg:#f4f5f7; --panel:#fbfbfc; --panel-2:#f7f8fa; --ink:#111318;
  --ink-2:#4b515c; --muted:#858b96; --line:#dfe2e7; --line-2:#cbd0d8;
  --blue:#356df3; --blue-soft:#e8efff; --green:#13885a; --green-soft:#e3f5ed;
  --amber:#ad6b05; --amber-soft:#fff1d6; --red:#c33d49; --red-soft:#fde8ea;
  --violet:#7653d6; --shadow:0 12px 36px rgba(19,27,43,.07);
  --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;
}
@media (prefers-color-scheme: dark) {
  :root { color-scheme:dark; --bg:#0d0f12; --panel:#15181d; --panel-2:#111419;
    --ink:#f5f7fa; --ink-2:#bbc0c9; --muted:#777e89; --line:#292e36;
    --line-2:#3a414c; --blue:#6b93ff; --blue-soft:#182542; --green:#48c892;
    --green-soft:#123226; --amber:#e4a847; --amber-soft:#362912; --red:#ef707c;
    --red-soft:#3a1b20; --violet:#a98afb; --shadow:0 18px 50px rgba(0,0,0,.28); }
}
*{box-sizing:border-box} html,body{height:100%;overflow:hidden} body{margin:0;background:var(--bg);color:var(--ink);
 font:13px/1.45 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
button,select,input,textarea{font:inherit;color:inherit} button{cursor:pointer}
.app{height:100vh;min-height:0;display:grid;grid-template-rows:62px minmax(0,1fr)}
header{height:62px;display:flex;align-items:center;gap:22px;padding:0 22px;
 background:color-mix(in srgb,var(--panel) 94%,transparent);border-bottom:1px solid var(--line);
 position:sticky;top:0;z-index:20;backdrop-filter:blur(16px)}
.brand{display:flex;align-items:center;gap:10px;min-width:186px;font-weight:720;letter-spacing:-.02em}
.brandmark{width:28px;height:28px;border-radius:9px;background:var(--ink);color:var(--panel);
 display:grid;place-items:center;font-size:15px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.16)}
nav{display:flex;align-items:center;gap:3px} nav a{padding:7px 10px;border-radius:8px;
 color:var(--ink-2);text-decoration:none;font-size:12px} nav a:hover{background:var(--panel-2);color:var(--ink)}
nav a[aria-current=page]{background:var(--blue-soft);color:var(--blue);font-weight:650}
.head-status{margin-left:auto;display:flex;align-items:center;gap:8px;color:var(--muted);font-size:11px}
.pulse{width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 0 4px var(--green-soft)}.pulse.attention{background:var(--amber);box-shadow:0 0 0 4px var(--amber-soft)}
.shell{height:calc(100vh - 62px);min-height:0;display:grid;grid-template-columns:252px minmax(520px,1fr) 296px;gap:0;overflow:hidden}
.rail,.inspect{height:100%;min-height:0;background:var(--panel);overflow-y:auto;overscroll-behavior:contain;scrollbar-gutter:stable}
.rail{border-right:1px solid var(--line);padding:17px 13px}.inspect{border-left:1px solid var(--line);padding:17px}
.eyebrow{font-size:9px;font-weight:750;letter-spacing:.13em;text-transform:uppercase;color:var(--muted);
 margin:2px 7px 8px}.flow-card,.run-card,.agent-row{width:100%;text-align:left;border:1px solid transparent;
 background:transparent;border-radius:10px;padding:9px 10px;margin:2px 0;color:var(--ink)}
.flow-card:hover,.run-card:hover,.agent-row:hover{background:var(--panel-2)}
.flow-card.active,.run-card.active{background:var(--blue-soft);border-color:color-mix(in srgb,var(--blue) 30%,var(--line));color:var(--blue)}
.flow-name,.run-name{display:flex;align-items:center;gap:7px;font-size:12px;font-weight:650}
.flow-card small,.run-card small{display:block;color:var(--muted);font-size:10px;margin:3px 0 0 17px}
.mini-dot{width:7px;height:7px;border-radius:50%;background:var(--line-2);flex:none}.mini-dot.running{background:var(--blue)}
.mini-dot.interrupted,.mini-dot.signaled,.mini-dot.launching{background:var(--amber)}.mini-dot.blocked,.mini-dot.failed,.mini-dot.lost,.mini-dot.launch_failed{background:var(--red)}.mini-dot.completed{background:var(--green)}
.divider{height:1px;background:var(--line);margin:16px 7px}.agent-row{display:grid;grid-template-columns:27px 1fr;gap:8px;align-items:center}
#runList{max-height:min(42vh,430px);overflow-y:auto;overscroll-behavior:contain;padding-right:3px}.older-runs{display:block;padding:8px 10px;color:var(--muted);font-size:10px;text-decoration:none}.older-runs:hover{color:var(--blue)}
.job-card{width:100%;text-align:left;border:1px solid var(--line);background:var(--panel-2);border-radius:9px;padding:8px 9px;margin:5px 0}.job-card:hover,.job-card.active{border-color:var(--blue);background:var(--blue-soft)}.job-head{display:flex;align-items:center;gap:7px}.job-head strong{min-width:0;flex:1;font-size:10.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.job-card small{display:block;margin:3px 0 0 14px;color:var(--muted);font:8.5px var(--mono);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#jobList{max-height:220px;overflow-y:auto;padding-right:3px}.lock-line{display:flex;align-items:center;gap:6px;margin:0 7px 7px;color:var(--muted);font-size:9px}.lock-mark{width:15px;height:15px;border:1px solid var(--line-2);border-radius:5px;display:grid;place-items:center;font-size:8px;color:var(--green);background:var(--green-soft)}.job-output{max-height:180px;overflow:auto;white-space:pre-wrap;word-break:break-word;font:9px/1.5 var(--mono);background:var(--panel-2);border:1px solid var(--line);padding:7px;border-radius:7px}.job-events{margin-top:10px;border-top:1px solid var(--line);padding-top:8px}.job-event{display:grid;grid-template-columns:7px 1fr;gap:7px;margin:7px 0}.job-event i{width:7px;height:7px;border-radius:50%;background:var(--blue);margin-top:4px}.job-event strong{display:block;font-size:9.5px}.job-event span{display:block;color:var(--muted);font-size:8.5px}
.agent-avatar{width:27px;height:27px;display:grid;place-items:center;border-radius:9px;background:var(--panel-2);
 border:1px solid var(--line);font-size:10px;font-weight:800;color:var(--ink-2)}
.agent-row strong{display:block;font-size:11px}.agent-row span{display:block;color:var(--muted);font-size:9.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.center{width:100%;max-width:100%;height:100%;min-width:0;min-height:0;display:grid;grid-template-rows:max-content max-content max-content minmax(220px,1fr) max-content;overflow:hidden}
.toolbar{grid-row:1;width:100%;max-width:100%;min-width:0;min-height:72px;padding:11px 18px;display:flex;align-items:center;gap:12px;border-bottom:1px solid var(--line);
 background:var(--panel)}.title-wrap{min-width:0}.workflow-kicker{display:block;margin-bottom:2px;color:var(--blue);font-size:8.5px;font-weight:760;letter-spacing:.11em;text-transform:uppercase}.title-wrap h1{font-size:17px;letter-spacing:-.025em;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.title-wrap p{font-size:10.5px;color:var(--muted);margin:2px 0 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.toolbar-actions{margin-left:auto;display:flex;gap:6px;align-items:center}.seg{display:flex;padding:3px;border:1px solid var(--line);background:var(--panel-2);border-radius:9px}
.seg button,.icon-btn{border:0;background:transparent;border-radius:6px;padding:5px 8px;color:var(--muted);font-size:11px}
.seg button.active{background:var(--panel);box-shadow:0 1px 4px rgba(0,0,0,.08);color:var(--ink)}
.icon-btn{border:1px solid var(--line);background:var(--panel);min-width:29px}.icon-btn:hover{color:var(--ink);border-color:var(--line-2)}
.scope-bar{grid-row:2;display:grid;grid-template-columns:minmax(115px,.8fr) 48px minmax(115px,.8fr) 48px minmax(210px,1.45fr) 48px minmax(95px,.65fr);gap:6px;align-items:center;padding:9px 18px;border-bottom:1px solid var(--line);background:var(--panel-2)}.scope-item{min-width:0;display:grid;grid-template-columns:22px minmax(0,1fr);gap:7px;align-items:center}.scope-number{width:22px;height:22px;border:1px solid var(--line-2);border-radius:7px;display:grid;place-items:center;color:var(--muted);font-size:9px;font-weight:800;background:var(--panel)}.scope-copy{min-width:0}.scope-copy strong{display:block;font-size:9px;letter-spacing:.08em;text-transform:uppercase}.scope-copy small,.scope-copy a{display:block;min-width:0;color:var(--muted);font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.scope-copy a{color:var(--blue);text-decoration:none}.scope-copy a:hover{text-decoration:underline}.scope-arrow{position:relative;color:var(--muted);font-size:8px;text-align:center;white-space:nowrap}.scope-arrow::after{content:"";display:block;height:1px;margin-top:3px;background:linear-gradient(90deg,var(--line-2) calc(100% - 5px),transparent 0);clip-path:polygon(0 35%,calc(100% - 5px) 35%,calc(100% - 5px) 0,100% 50%,calc(100% - 5px) 100%,calc(100% - 5px) 65%,0 65%)}.run-picker select{width:100%;min-width:0;margin-top:3px;padding:5px 25px 5px 7px;border:1px solid var(--line-2);border-radius:7px;background:var(--panel);font-size:10px}.run-picker .scope-number{border-color:color-mix(in srgb,var(--blue) 45%,var(--line));color:var(--blue);background:var(--blue-soft)}
.mobile-node-inspector{grid-row:3;display:none;align-items:center;gap:9px;min-width:0;padding:9px 12px;border-bottom:1px solid var(--line);background:var(--panel)}.mobile-node-inspector[hidden]{display:none!important}.mobile-node-inspector .mobile-accent{width:3px;align-self:stretch;border-radius:3px;background:var(--blue)}.mobile-node-inspector .mobile-copy{flex:1;min-width:0}.mobile-node-inspector strong{display:block;font-size:11px}.mobile-node-inspector span{display:block;color:var(--muted);font-size:9.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mobile-node-inspector button{margin-left:auto;border:0;background:transparent;color:var(--muted);padding:5px 7px;border-radius:6px}.mobile-node-inspector button:hover{background:var(--panel-2);color:var(--ink)}
.zoom-level{min-width:38px;color:var(--muted);font:9.5px var(--mono);text-align:center}.canvas-frame{grid-row:4;width:100%;max-width:100%;min-width:0;min-height:0;position:relative;overflow:hidden}.canvas{width:100%;height:100%;max-width:100%;min-width:0;min-height:0;position:relative;overflow:auto;overscroll-behavior:contain;touch-action:none;user-select:none;cursor:grab;background-color:var(--bg);background-image:radial-gradient(var(--line) .75px,transparent .75px);
 background-size:18px 18px}.canvas.panning{cursor:grabbing}.canvas svg{display:block}.canvas-hint{position:absolute;right:14px;bottom:12px;pointer-events:none;
 padding:5px 8px;border:1px solid var(--line);border-radius:7px;background:color-mix(in srgb,var(--panel) 88%,transparent);color:var(--muted);font-size:9.5px;backdrop-filter:blur(8px)}
.edge-legend{position:absolute;left:13px;top:12px;z-index:3;display:flex;align-items:center;gap:10px;pointer-events:none;padding:6px 8px;border:1px solid var(--line);border-radius:8px;background:color-mix(in srgb,var(--panel) 91%,transparent);color:var(--muted);font-size:9px;box-shadow:0 2px 9px rgba(19,27,43,.04);backdrop-filter:blur(10px)}
.edge-legend span{display:flex;align-items:center;gap:4px;white-space:nowrap}.edge-swatch{position:relative;width:18px;height:6px;display:inline-block;color:var(--line-2)}.edge-swatch::before{content:"";position:absolute;left:0;right:2px;top:2px;border-top:2px solid currentColor}.edge-swatch::after{content:"";position:absolute;right:0;top:0;border-left:4px solid currentColor;border-top:3px solid transparent;border-bottom:3px solid transparent}.edge-swatch.loop::before{border-top-style:dashed}.edge-swatch.observed{color:var(--green)}.edge-swatch.active{color:var(--blue)}
.edge{fill:none;stroke:var(--line-2);stroke-width:1.2;marker-end:url(#arrow);transition:stroke .15s,stroke-width .15s}.edge.loop{stroke-dasharray:5 5}.edge.visited{stroke:color-mix(in srgb,var(--green) 70%,var(--line));stroke-width:1.5}.edge.active{stroke:var(--blue);stroke-width:2;stroke-dasharray:7 5;animation:flow 1s linear infinite}.edge.hovered,.edge.selected{stroke:var(--blue);stroke-width:2.2}
@keyframes flow{to{stroke-dashoffset:-12}}.edge-hit{fill:none;stroke:transparent;stroke-width:16;pointer-events:stroke;cursor:pointer}.edge-hit:focus{outline:none}.edge-label-group{cursor:pointer;outline:none}.edge-label-bg{fill:color-mix(in srgb,var(--panel) 94%,transparent);stroke:var(--line-2);stroke-width:1;filter:url(#labelShadow)}.edge-label-text{font-size:10px;fill:var(--ink-2);font-weight:680;letter-spacing:.01em}.edge-label-group:hover .edge-label-bg,.edge-label-group:focus .edge-label-bg,.edge-label-group.selected .edge-label-bg{fill:var(--blue-soft);stroke:var(--blue);stroke-width:1.4}.edge-label-group:hover .edge-label-text,.edge-label-group:focus .edge-label-text,.edge-label-group.selected .edge-label-text{fill:var(--blue)}
.node{cursor:grab;touch-action:none}.node.dragging{cursor:grabbing}.node.dragging .box{stroke:var(--blue);stroke-width:2}.node .box{fill:var(--panel);stroke:var(--line-2);stroke-width:1;filter:url(#softShadow)}
.node:hover .box,.node:focus .box,.node.selected .box{stroke:var(--blue);stroke-width:1.8}.node:focus{outline:none}.node.visited .box{stroke:color-mix(in srgb,var(--green) 70%,var(--line))}
.node.current .box{stroke:var(--blue);stroke-width:2.1;animation:ring 1.7s ease-in-out infinite}.node.blocked .box{stroke:var(--red);stroke-width:2}.node.waiting .box{stroke:var(--amber);stroke-width:2}
@keyframes ring{50%{stroke-opacity:.45}}.node .accent{fill:var(--node-accent,var(--line-2))}.node .kind{font-size:8px;letter-spacing:.11em;text-transform:uppercase;fill:var(--muted);font-weight:700}.node .label{font-size:12px;fill:var(--ink);font-weight:680}.node .desc{font-size:9px;fill:var(--muted)}
.node .state-dot{fill:var(--line-2)}.node.visited .state-dot{fill:var(--green)}.node.current .state-dot{fill:var(--blue)}.node.blocked .state-dot{fill:var(--red)}.node.waiting .state-dot{fill:var(--amber)}
.run-strip{grid-row:5;width:100%;max-width:100%;min-width:0;overflow:hidden;border-top:1px solid var(--line);background:var(--panel);padding:12px 18px;min-height:116px}.run-strip-head{display:flex;align-items:center;gap:8px;min-width:0;margin-bottom:8px}.run-strip-head strong{font-size:11px;flex:none}.run-strip-head span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px;color:var(--muted)}
.event-row{display:flex;width:100%;max-width:100%;min-width:0;gap:0;overflow-x:auto;overscroll-behavior:contain;padding:2px}.event-pill{position:relative;min-width:116px;max-width:170px;padding:7px 9px 7px 13px;border-left:2px solid var(--line-2);background:var(--panel-2);margin-right:4px;border-radius:0 7px 7px 0}
.event-pill.current{border-color:var(--blue);background:var(--blue-soft)}.event-pill b{display:block;font-size:9.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.event-pill span{font-size:8.5px;color:var(--muted)}
.empty{padding:14px;color:var(--muted);font-size:11px}.inspect h2{font-size:13px;margin:1px 0 4px;letter-spacing:-.01em}.inspect .lede{font-size:11px;color:var(--ink-2);margin:0 0 14px}.meta-grid{display:grid;grid-template-columns:82px 1fr;gap:7px 8px;border-top:1px solid var(--line);padding-top:12px;margin-top:12px;font-size:10.5px}.meta-grid .k{color:var(--muted)}
.chips{display:flex;flex-wrap:wrap;gap:4px;margin-top:8px}.chip{font:9px var(--mono);padding:3px 6px;border:1px solid var(--line);border-radius:6px;background:var(--panel-2);color:var(--ink-2)}
.risk{display:inline-flex;padding:2px 7px;border-radius:999px;font-size:9px;font-weight:750;text-transform:uppercase}.risk.low{background:var(--green-soft);color:var(--green)}.risk.medium,.risk.unknown{background:var(--amber-soft);color:var(--amber)}.risk.active{background:var(--blue-soft);color:var(--blue)}.risk.high{background:var(--red-soft);color:var(--red)}
.queue{margin-top:22px}.approval{border:1px solid color-mix(in srgb,var(--amber) 40%,var(--line));border-radius:11px;padding:11px;margin:8px 0;background:var(--amber-soft)}
.approval-head{display:flex;align-items:center;justify-content:space-between;gap:6px}.approval-head strong{font-size:10.5px}.approval p{font-size:10px;color:var(--ink-2);margin:7px 0}.target{font:9px/1.4 var(--mono);word-break:break-all;color:var(--ink-2);padding:6px;background:color-mix(in srgb,var(--panel) 55%,transparent);border-radius:6px}
.approval details{margin-top:7px}.approval summary{cursor:pointer;font-size:9.5px;color:var(--ink-2)}.approval pre{max-height:150px;overflow:auto;white-space:pre-wrap;word-break:break-word;font:9px/1.45 var(--mono);background:var(--panel);border:1px solid var(--line);padding:7px;border-radius:7px}
.decision{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:8px}.decision button{border:1px solid var(--line);border-radius:7px;padding:6px;background:var(--panel);font-size:10px}.decision .approve{border-color:var(--green);color:var(--green)}.decision .deny{border-color:var(--red);color:var(--red)}
.queue-head{display:flex;align-items:flex-start;justify-content:space-between;gap:6px}.queue-head .eyebrow{margin-left:0}.queue-help{margin:-3px 0 8px;color:var(--muted);font-size:9px;line-height:1.4}.seg.compact{flex:none}.seg.compact button{font-size:8.5px;padding:3px 5px}.soundness-context{border:1px solid var(--line);border-radius:8px;padding:7px 8px;background:var(--panel-2);margin-bottom:8px}.soundness-context strong{display:block;font-size:9.5px}.soundness-context span{display:block;color:var(--muted);font-size:8.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.soundness-card{border:1px solid var(--line);border-left:3px solid #1689a7;border-radius:9px;padding:9px;margin:7px 0;background:var(--panel-2)}.soundness-card header{height:auto;padding:0;border:0;background:transparent;display:flex;justify-content:space-between;gap:8px}.soundness-card strong{font-size:10px}.soundness-card p{font-size:9.5px;line-height:1.45;color:var(--ink-2);margin:6px 0}.soundness-card small{display:block;font-size:8.5px;color:var(--muted)}.soundness-origin{margin:6px 0;padding:6px;border-radius:6px;background:var(--panel);border:1px solid var(--line)}.soundness-origin b{display:block;font-size:8.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.soundness-origin span{display:block;color:var(--muted);font:8px var(--mono);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.soundness-card details{margin-top:5px}.soundness-card summary{font-size:9px;color:var(--muted);cursor:pointer}.soundness-focus{width:100%;margin-top:7px;border:1px solid var(--line);border-radius:6px;background:var(--panel);color:var(--blue);padding:5px;font-size:9px}.soundness-focus:hover{border-color:var(--blue)}.soundness-card pre,.event-data{max-height:150px;overflow:auto;white-space:pre-wrap;word-break:break-word;font:8.5px/1.45 var(--mono);background:var(--panel);border:1px solid var(--line);padding:6px;border-radius:6px}
.confirm-dialog{width:min(470px,calc(100vw - 28px));border:1px solid var(--line);border-radius:14px;padding:0;background:var(--panel);color:var(--ink);box-shadow:0 28px 90px rgba(0,0,0,.28)}.confirm-dialog::backdrop{background:rgba(8,11,17,.46);backdrop-filter:blur(3px)}.dialog-head{padding:17px 18px 12px;border-bottom:1px solid var(--line)}.dialog-head .eyebrow{margin:0 0 5px}.dialog-head h2{margin:0;font-size:16px}.dialog-body{padding:15px 18px}.dialog-body p{font-size:11px;color:var(--ink-2);margin:0 0 10px}.dialog-call{max-height:160px;overflow:auto;padding:9px;border:1px solid var(--line);border-radius:8px;background:var(--panel-2);white-space:pre-wrap;word-break:break-word;font:9.5px/1.5 var(--mono)}.dialog-body label{display:block;margin-top:12px;font-size:10px;color:var(--muted)}.dialog-body textarea{width:100%;min-height:64px;resize:vertical;margin-top:5px;border:1px solid var(--line-2);border-radius:8px;padding:8px;background:var(--panel-2)}.dialog-actions{display:flex;justify-content:flex-end;gap:7px;padding:11px 18px 16px}.dialog-actions button{border:1px solid var(--line);border-radius:8px;padding:7px 12px;background:var(--panel)}.dialog-actions .confirm-approve{background:var(--green);border-color:var(--green);color:white}.dialog-actions .confirm-deny{background:var(--red);border-color:var(--red);color:white}
.toast{position:fixed;right:18px;bottom:18px;padding:9px 12px;background:var(--ink);color:var(--panel);border-radius:8px;font-size:11px;box-shadow:var(--shadow);opacity:0;transform:translateY(8px);pointer-events:none;transition:.2s}.toast.show{opacity:1;transform:none}
@media(max-width:1050px){.shell{grid-template-columns:220px minmax(0,1fr)}.inspect{display:none}.mobile-node-inspector{display:flex}.scope-bar{grid-template-columns:minmax(105px,.75fr) 42px minmax(105px,.75fr) 42px minmax(185px,1.4fr) 42px minmax(88px,.6fr);padding-inline:12px}.scope-arrow{font-size:7px}} @media(max-width:720px){header{padding:0 12px}.brand{min-width:0}.brand span:last-child{display:none}nav a{padding:6px}.head-status{display:none}.shell{grid-template-columns:minmax(0,1fr)}.rail{display:none}.toolbar{display:grid;grid-template-columns:minmax(0,1fr);align-items:start;padding:10px 12px;gap:8px}.toolbar-actions{width:100%;margin-left:0;justify-content:space-between}.toolbar-actions .seg{display:flex}.toolbar-actions #zoomOut,.toolbar-actions #zoomIn,.zoom-level{display:none}.scope-bar{display:grid;grid-template-columns:minmax(80px,.75fr) minmax(90px,.85fr) minmax(190px,1.6fr) minmax(82px,.65fr);gap:5px 8px;padding:7px 9px}.scope-bar::before{content:"Endeavor contains conversations · conversations trigger task runs · task runs record decision events";grid-column:1/-1;color:var(--muted);font-size:7px;letter-spacing:.03em}.scope-copy strong{font-size:8px}.scope-copy small,.scope-copy a{font-size:8px}.scope-number,.scope-arrow{display:none}.scope-item{display:block}.run-picker select{font-size:9px}.center{height:100%;min-height:0}.run-strip{min-height:104px;padding:10px 12px}}
@media(max-height:700px){.toolbar{min-height:62px;padding-top:9px;padding-bottom:9px}.run-strip{min-height:96px;padding-top:9px;padding-bottom:9px}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>
</head>
<body>
<div class="app">
<header>
  <div class="brand"><span class="brandmark">⌁</span><span>llm-super</span></div>
  <nav aria-label="Primary"><a href="/workspace">Workspace</a><a href="/">Live</a><a href="/history">History</a><a href="/graphs" aria-current="page">Agent Graphs</a></nav>
  <div class="head-status"><span class="pulse"></span><span id="syncState">control plane live</span></div>
</header>
<div class="shell">
  <aside class="rail">
    <div class="eyebrow">Workflow definitions</div><div id="flowList"></div>
    <div class="divider"></div><div class="eyebrow">Task runs for this workflow</div><div id="runList"><div class="empty">No task runs yet.</div></div>
    <div class="divider"></div><div class="eyebrow">Remote jobs</div><div class="lock-line"><span class="lock-mark">▣</span><span id="executionLock">backend locked</span></div><div id="jobList"><div class="empty">No durable jobs yet.</div></div>
    <div class="divider"></div><div class="eyebrow">Agent identities</div><div id="agentList"></div>
  </aside>
  <main class="center">
    <div class="toolbar">
      <div class="title-wrap"><span class="workflow-kicker">Reusable workflow definition · not a conversation map</span><h1 id="flowTitle">Agent orchestration</h1><p id="flowDescription">Loading the declared control plane…</p></div>
      <div class="toolbar-actions">
        <div class="seg" aria-label="Graph view"><button id="definitionMode" class="active" aria-pressed="true">Workflow only</button><button id="runMode" aria-pressed="false">Latest task run</button></div>
        <button class="icon-btn" id="zoomOut" title="Zoom out" aria-label="Zoom out">−</button><span class="zoom-level" id="zoomLevel" aria-live="polite">82%</span><button class="icon-btn" id="fit" title="Fit graph" aria-label="Fit graph to viewport">Fit</button><button class="icon-btn" id="resetLayout" title="Reset node layout" aria-label="Reset node layout">Reset</button><button class="icon-btn" id="zoomIn" title="Zoom in" aria-label="Zoom in">＋</button>
      </div>
    </div>
    <section class="scope-bar" aria-label="Endeavor, conversation, task run, and decision event hierarchy">
      <div class="scope-item"><span class="scope-number">1</span><span class="scope-copy"><strong>Endeavor</strong><a id="endeavorLink" href="/history">Select a task run first</a><small id="endeavorMeta">Broader objective</small></span></div>
      <span class="scope-arrow">contains</span>
      <div class="scope-item"><span class="scope-number">2</span><span class="scope-copy"><strong>Conversation</strong><a id="conversationLink" href="/history">No conversation selected</a><small id="conversationMeta">One chat thread</small></span></div>
      <span class="scope-arrow">triggers</span>
      <label class="scope-item run-picker" for="runPicker"><span class="scope-number">3</span><span class="scope-copy"><strong>Task run</strong><select id="runPicker" aria-label="Select an observed task run"><option value="">Choose a task run…</option></select></span></label>
      <span class="scope-arrow">records</span>
      <div class="scope-item"><span class="scope-number">4</span><span class="scope-copy"><strong>Decision events</strong><small id="decisionMeta">Select a task run</small></span></div>
    </section>
    <section class="mobile-node-inspector" id="mobileNodeInspector" aria-live="polite" hidden></section>
    <div class="canvas-frame"><div class="canvas" id="canvas"><svg id="graph" role="group" aria-label="Reusable agent workflow with an optional task-run overlay"></svg></div><div class="edge-legend" id="edgeLegend" aria-label="Edge legend"><span><i class="edge-swatch"></i>forward route</span><span><i class="edge-swatch loop"></i>recovery loop</span><span><i class="edge-swatch observed"></i>observed</span><span><i class="edge-swatch active"></i>active</span></div><div class="canvas-hint">Canvas = reusable workflow · selected task run colors its observed path</div></div>
    <section class="run-strip" aria-live="polite"><div class="run-strip-head"><strong>Selected task run · decision trail</strong><span id="trailMeta">Choose a task run above to overlay its observed execution.</span></div><div class="event-row" id="eventTrail"></div></section>
  </main>
  <aside class="inspect">
    <div class="eyebrow">Inspector</div><div id="nodeInspector"><div class="empty">Select a node to inspect its identity, capability boundary, and latest observed event.</div></div>
    <section class="queue"><div class="eyebrow">Approval queue</div><div id="approvalQueue"><div class="empty">No actions need you.</div></div></section>
    <section class="queue"><div class="queue-head"><div><div class="eyebrow">Soundness checks</div><p class="queue-help">Independent tests of claims—not an overall task grade.</p></div><div class="seg compact" aria-label="Soundness scope"><button id="soundnessSelected" class="active" aria-pressed="true">This run</button><button id="soundnessAll" aria-pressed="false">All recent</button></div></div><div id="soundnessContext"></div><div id="soundnessQueue"><div class="empty">Choose a task run to see its checks.</div></div></section>
  </aside>
</div>
<dialog class="confirm-dialog" id="decisionDialog" aria-labelledby="decisionTitle">
  <div class="dialog-head"><div class="eyebrow">Explicit operator boundary</div><h2 id="decisionTitle">Review action</h2></div>
  <div class="dialog-body"><p id="decisionReason"></p><pre class="dialog-call" id="decisionCall"></pre><label for="decisionNote">Decision note <span id="noteHint">(recommended)</span></label><textarea id="decisionNote" placeholder="Record the evidence behind this decision"></textarea></div>
  <div class="dialog-actions"><button id="decisionCancel">Cancel</button><button id="decisionConfirm">Confirm</button></div>
</dialog>
<div class="toast" id="toast"></div>
<script>
const $=s=>document.querySelector(s); const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const positionKey="llm-super.graph-node-positions.v1";
function loadNodePositions(){try{const value=JSON.parse(localStorage.getItem(positionKey)||"{}");return value&&typeof value==="object"?value:{}}catch{return{}}}
const state={defs:null,flow:null,runs:[],run:null,actions:[],jobs:[],executionLock:null,selectedJob:null,selectedNode:null,selectedEdge:null,soundnessScope:"selected",endeavorBySession:{},zoom:.82,autoFit:false,mode:"definition",serial:0,pendingDecision:null,nodePositions:loadNodePositions(),rendered:null,gesture:null,graphSignature:null,ignoreClickUntil:0};
const accent={cobalt:"#356df3",amber:"#d28a17",violet:"#7653d6",cyan:"#1689a7",emerald:"#13885a",rose:"#d34d64",slate:"#7b8492"};
function toast(text){const el=$("#toast");el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
async function api(path,options){const r=await fetch(path,options);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||r.statusText);return r.json()}
function flowById(id){return state.defs?.flows.find(f=>f.id===id)} function agentById(id){return state.defs?.agents.find(a=>a.id===id)}
function short(value,limit){const text=String(value||"");return text.length>limit?text.slice(0,limit-1)+"…":text}
function runTaskLabel(run){return String(run?.task_label||run?.input?.goal||run?.input?.label||run?.task||run?.run_id||"Task run")}
function runConversationLabel(run){return String(run?.conversation_title||`Conversation ${run?.session||"unknown"}`)}
function historyURL(session){return session&&session!=="-"?`/history?q=${encodeURIComponent(session)}`:"/history"}
function runTimestamp(run){return run?.updated_at?new Date(run.updated_at*1000).toLocaleString([], {month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):"time unavailable"}
function endeavorFor(run){return run?.session?state.endeavorBySession[run.session]:null}
async function loadEndeavorContext(run){const session=run?.session;if(!session||session==="-"||Object.prototype.hasOwnProperty.call(state.endeavorBySession,session))return;state.endeavorBySession[session]={loading:true};if(state.run?.session===session){renderScope();renderSoundness()}try{state.endeavorBySession[session]=await api(`/admin/history/sessions/${encodeURIComponent(session)}/context`)}catch{state.endeavorBySession[session]=null}if(state.run?.session===session){renderScope();renderSoundness()}}
function jobOutput(label,value,limit=8192){const raw=String(value||"");if(!raw)return"";const clipped=raw.length>limit?`[showing final ${limit} characters; earlier output remains in the durable ledger]\n${raw.slice(-limit)}`:raw;return`${label}\n${clipped}`}
function clamp(value,min,max){return Math.max(min,Math.min(max,value))}
function persistNodePositions(){try{localStorage.setItem(positionKey,JSON.stringify(state.nodePositions))}catch{}}
function nodeState(id){if(!state.run||state.mode!=="run")return "";const events=state.run.events||[];const visited=events.some(e=>e.node_id===id);const latest=events[events.length-1];if(id===state.run.current_node){if(state.run.status==="blocked"||state.run.status==="failed")return "blocked";if(state.run.status==="interrupted"||id==="human_approval")return "waiting";return "current"}return visited?"visited":""}
function eventFor(id){return [...(state.run?.events||[])].reverse().find(e=>e.node_id===id)}
function layout(flow){
 const forward=flow.edges.filter(e=>!e.loop),indeg=new Map(flow.nodes.map(n=>[n.id,0]));
 forward.forEach(e=>indeg.set(e.target,(indeg.get(e.target)||0)+1));
 const q=[flow.entry,...flow.nodes.filter(n=>n.id!==flow.entry&&indeg.get(n.id)===0).map(n=>n.id)],layer=new Map([[flow.entry,0]]),seen=new Set();
 while(q.length){const id=q.shift();if(seen.has(id))continue;seen.add(id);for(const e of forward.filter(x=>x.source===id)){layer.set(e.target,Math.max(layer.get(e.target)||0,(layer.get(id)||0)+1));indeg.set(e.target,indeg.get(e.target)-1);if(indeg.get(e.target)<=0)q.push(e.target)}}
 flow.nodes.forEach(n=>{if(!layer.has(n.id))layer.set(n.id,0)});
 const groups={};flow.nodes.forEach(n=>(groups[layer.get(n.id)]??=[]).push(n));
 const W=202,H=76,X=102,Y=34,pad=52,maxRows=Math.max(...Object.values(groups).map(g=>g.length)),contentHeight=maxRows*H+(maxRows-1)*Y;
 const width=pad*2+(Math.max(...layer.values())+1)*W+Math.max(...layer.values())*X,height=Math.max(430,pad*2+contentHeight),top=(height-contentHeight)/2,pos={};
 for(const [l,group] of Object.entries(groups)){const offset=(maxRows-group.length)*(H+Y)/2;group.forEach((n,i)=>pos[n.id]={x:pad+Number(l)*(W+X),y:top+offset+i*(H+Y),w:W,h:H})}
 const saved=state.nodePositions[flow.id]||{};
 for(const [id,p] of Object.entries(saved)){if(!pos[id]||!Number.isFinite(Number(p.x))||!Number.isFinite(Number(p.y)))continue;pos[id].x=clamp(Number(p.x),18,width-W-18);pos[id].y=clamp(Number(p.y),18,height-H-18)}
 return{pos,width,height}
}
function edgePath(a,b,loop){const sx=a.x+a.w,sy=a.y+a.h/2,tx=b.x,ty=b.y+b.h/2;if(loop||tx<=sx){const lift=Math.min(sy,ty)-58;return`M${sx} ${sy} C${sx+48} ${lift},${tx-48} ${lift},${tx} ${ty}`}const d=Math.max(36,(tx-sx)*.46);return`M${sx} ${sy} C${sx+d} ${sy},${tx-d} ${ty},${tx} ${ty}`}
function edgeCaption(edge){return edge.label||edge.condition||(edge.loop?"retry":"continue")}
function edgeLabelPoint(a,b,loop){const sx=a.x+a.w,sy=a.y+a.h/2,tx=b.x,ty=b.y+b.h/2;if(loop||tx<=sx)return{x:(sx+tx)/2,y:Math.min(sy,ty)-58};return{x:sx+(tx-sx)*.5,y:sy+(ty-sy)*.5-10}}
function edgeLabelLayout(flow,pos){const placed=[];return flow.edges.map(edge=>{const a=pos[edge.source],b=pos[edge.target],caption=edgeCaption(edge),shown=short(caption,24),width=Math.max(42,Math.min(154,shown.length*5.8+18)),base=edgeLabelPoint(a,b,edge.loop),offsets=edge.loop?[0,-22,22,-44,44,-66,66]:[0,22,-22,44,-44,66,-66];let point=base;for(const offset of offsets){const candidate={x:base.x,y:base.y+offset},rect={left:candidate.x-width/2-4,right:candidate.x+width/2+4,top:candidate.y-13,bottom:candidate.y+13};if(!placed.some(other=>rect.left<other.right&&rect.right>other.left&&rect.top<other.bottom&&rect.bottom>other.top)){point=candidate;placed.push(rect);break}}return{caption,shown,width,point}})}
function edgeRuntimeState(edge){if(!state.run||state.mode!=="run")return"declared";if(edge.source===state.run.current_node&&state.run.status==="running")return"active";const events=state.run.events||[];for(let i=1;i<events.length;i++)if(events[i-1].node_id===edge.source&&events[i].node_id===edge.target)return"observed";return"not observed"}
function fitScale(flow){const {width,height}=layout(flow),canvas=$("#canvas");return Math.max(.22,Math.min(1,(Math.max(280,canvas.clientWidth)-48)/width,(Math.max(180,canvas.clientHeight)-48)/height))}
function renderGraph(){
 const flow=state.flow;if(!flow||state.gesture)return;
 const canvas=$("#canvas"),{pos,width,height}=layout(flow);
 if(state.autoFit)state.zoom=fitScale(flow);
 const signature=JSON.stringify([flow.id,state.mode,state.run?.run_id,state.run?.status,state.run?.current_node,state.run?.updated_at,(state.run?.events||[]).length,state.selectedNode,state.selectedEdge,state.zoom,state.autoFit,canvas.clientWidth,canvas.clientHeight,state.nodePositions[flow.id]||{}]);
 if(signature===state.graphSignature&&$("#graph .node"))return;
 const zoom=state.zoom,surfaceWidth=Math.max(canvas.clientWidth,Math.ceil(width*zoom+48)),surfaceHeight=Math.max(canvas.clientHeight,Math.ceil(height*zoom+48));
 const offsetX=Math.max(24,(surfaceWidth-width*zoom)/2),offsetY=Math.max(24,(surfaceHeight-height*zoom)/2);
 const events=state.run?.events||[],transitions=new Set(),edgeLabels=edgeLabelLayout(flow,pos);
 for(let i=1;i<events.length;i++){if(events[i-1].node_id!==events[i].node_id)transitions.add(events[i-1].node_id+">"+events[i].node_id)}
 const current=state.run?.current_node;
 let svg=`<title>${esc(flow.label)}</title><desc>${esc(flow.description)} Arrows show transition direction. Solid edges are forward routes; dashed edges are recovery loops. Select a node or edge to inspect its declaration and runtime evidence.</desc><defs><marker id="arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L8 4L0 8Z" fill="context-stroke"/></marker><filter id="softShadow" x="-20%" y="-30%" width="140%" height="160%"><feDropShadow dx="0" dy="3" stdDeviation="4" flood-opacity=".08"/></filter><filter id="labelShadow" x="-15%" y="-40%" width="130%" height="180%"><feDropShadow dx="0" dy="1" stdDeviation="2" flood-opacity=".1"/></filter></defs><g class="viewport" transform="translate(${offsetX} ${offsetY}) scale(${zoom})">`;
	for(const [index,e] of flow.edges.entries()){const a=pos[e.source],b=pos[e.target];let cls="edge"+(e.loop?" loop":"");if(state.mode==="run"&&transitions.has(e.source+">"+e.target))cls+=" visited";if(state.mode==="run"&&e.source===current)cls+=" active";if(state.selectedEdge===index)cls+=" selected";const d=edgePath(a,b,e.loop),label=edgeLabels[index],edgeData=`data-edge-index="${index}" data-edge-source="${esc(e.source)}" data-edge-target="${esc(e.target)}" data-edge-loop="${e.loop?"1":"0"}"`,source=flow.nodes.find(n=>n.id===e.source)?.label||e.source,target=flow.nodes.find(n=>n.id===e.target)?.label||e.target,aria=`${label.caption}: ${source} to ${target}. ${e.loop?"Recovery loop":"Forward route"}.`;svg+=`<path class="${cls}" ${edgeData} d="${d}"/><path class="edge-hit" ${edgeData} d="${d}" aria-hidden="true"/><g class="edge-label-group${state.selectedEdge===index?" selected":""}" ${edgeData} transform="translate(${label.point.x} ${label.point.y})" tabindex="0" role="button" aria-label="${esc(aria)}"><rect class="edge-label-bg" x="${-label.width/2}" y="-9" width="${label.width}" height="18" rx="9"/><text class="edge-label-text" y="3.5" text-anchor="middle">${esc(label.shown)}</text></g>`}
for(const n of flow.nodes){const p=pos[n.id],ag=agentById(n.agent),ns=nodeState(n.id),sel=state.selectedNode===n.id?" selected":"";const description=n.description||ag?.role||"Declared graph boundary";svg+=`<g class="node ${ns}${sel}" data-node="${esc(n.id)}" transform="translate(${p.x} ${p.y})" style="--node-accent:${accent[ag?.accent]||accent.slate}" tabindex="0" role="button" aria-label="${esc(n.label+". "+description+" Drag to reposition; press Enter for details.")}"><rect class="box" width="${p.w}" height="${p.h}" rx="11"/><path class="accent" d="M0 11Q0 0 11 0H14V${p.h}H11Q0 ${p.h} 0 ${p.h-11}Z"/><circle class="state-dot" cx="${p.w-13}" cy="13" r="4"/><text class="kind" x="27" y="19">${esc(short(n.type+(ag?" · "+ag.label:""),33))}</text><text class="label" x="27" y="40">${esc(short(n.label,27))}</text><text class="desc" x="27" y="58">${esc(short(description,39))}</text></g>`}
 svg+="</g>";
 const el=$("#graph");el.setAttribute("viewBox",`0 0 ${surfaceWidth} ${surfaceHeight}`);el.setAttribute("width",surfaceWidth);el.setAttribute("height",surfaceHeight);el.style.width=`${surfaceWidth}px`;el.style.height=`${surfaceHeight}px`;el.innerHTML=svg;
 state.rendered={pos,width,height,zoom,offsetX,offsetY};state.graphSignature=signature;
 $("#zoomLevel").textContent=`${Math.round(zoom*100)}%`;
 el.querySelectorAll(".node").forEach(n=>{n.onpointerdown=beginNodeDrag;n.onclick=()=>{if(performance.now()>=state.ignoreClickUntil)selectNode(n.dataset.node)};n.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();selectNode(n.dataset.node)}}});
 const edgeTargets=el.querySelectorAll(".edge-hit,.edge-label-group");edgeTargets.forEach(target=>{target.onclick=e=>{e.stopPropagation();selectEdge(Number(target.dataset.edgeIndex))};target.onmouseenter=()=>setEdgeHover(Number(target.dataset.edgeIndex),true);target.onmouseleave=()=>setEdgeHover(Number(target.dataset.edgeIndex),false);target.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();selectEdge(Number(target.dataset.edgeIndex))}}});
}
function setEdgeHover(index,on){const root=$("#graph");root.querySelector(`.edge[data-edge-index="${index}"]`)?.classList.toggle("hovered",on)}
function redrawMovedGeometry(nodeId){
 const rendered=state.rendered,root=$("#graph");if(!rendered)return;
 const p=rendered.pos[nodeId],node=root.querySelector(`[data-node="${CSS.escape(nodeId)}"]`);if(node)node.setAttribute("transform",`translate(${p.x} ${p.y})`);
	 root.querySelectorAll(`[data-edge-source="${CSS.escape(nodeId)}"],[data-edge-target="${CSS.escape(nodeId)}"]`).forEach(el=>{const a=rendered.pos[el.dataset.edgeSource],b=rendered.pos[el.dataset.edgeTarget];if(a&&b&&el.tagName.toLowerCase()==="path")el.setAttribute("d",edgePath(a,b,el.dataset.edgeLoop==="1"))});edgeLabelLayout(state.flow,rendered.pos).forEach((label,index)=>root.querySelector(`.edge-label-group[data-edge-index="${index}"]`)?.setAttribute("transform",`translate(${label.point.x} ${label.point.y})`))
}
function beginNodeDrag(e){
 if(state.gesture||!e.isPrimary||(e.pointerType==="mouse"&&e.button!==0)||!state.rendered)return;
 const node=e.currentTarget,id=node.dataset.node,p=state.rendered.pos[id];if(!p)return;
 state.gesture={type:"node",pointerId:e.pointerId,nodeId:id,flowId:state.flow.id,startClientX:e.clientX,startClientY:e.clientY,startX:p.x,startY:p.y,moved:false};
 node.classList.add("dragging");node.setAttribute("aria-grabbed","true");node.focus();node.setPointerCapture(e.pointerId);e.stopPropagation();e.preventDefault()
}
function beginCanvasPan(e){
 const canvas=$("#canvas");if(state.gesture||!e.isPrimary||(e.pointerType==="mouse"&&e.button!==0)||e.target.closest?.(".node,.edge-hit,.edge-label-group"))return;
 state.gesture={type:"pan",pointerId:e.pointerId,startClientX:e.clientX,startClientY:e.clientY,startScrollLeft:canvas.scrollLeft,startScrollTop:canvas.scrollTop,moved:false};
 canvas.classList.add("panning");canvas.setPointerCapture(e.pointerId);e.preventDefault()
}
function moveGesture(e){
 const g=state.gesture;if(!g||g.pointerId!==e.pointerId)return;
 const dx=e.clientX-g.startClientX,dy=e.clientY-g.startClientY;if(Math.hypot(dx,dy)>3)g.moved=true;
 if(g.type==="pan"){const canvas=$("#canvas");canvas.scrollLeft=g.startScrollLeft-dx;canvas.scrollTop=g.startScrollTop-dy}
 else{const rendered=state.rendered,p=rendered?.pos[g.nodeId];if(!p)return;p.x=clamp(g.startX+dx/rendered.zoom,18,rendered.width-p.w-18);p.y=clamp(g.startY+dy/rendered.zoom,18,rendered.height-p.h-18);redrawMovedGeometry(g.nodeId)}
 e.preventDefault()
}
function finishGesture(e,cancelled=false){
 const g=state.gesture;if(!g||g.pointerId!==e.pointerId)return;state.gesture=null;
 if(g.type==="pan"){const canvas=$("#canvas");canvas.classList.remove("panning");if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);return}
 const node=$("#graph").querySelector(`[data-node="${CSS.escape(g.nodeId)}"]`),p=state.rendered?.pos[g.nodeId];if(node){node.classList.remove("dragging");node.removeAttribute("aria-grabbed");if(node.hasPointerCapture(e.pointerId))node.releasePointerCapture(e.pointerId)}
 state.ignoreClickUntil=performance.now()+400;
 if(cancelled&&p){p.x=g.startX;p.y=g.startY;renderGraph();return}
 if(g.moved&&p){(state.nodePositions[g.flowId]??={})[g.nodeId]={x:p.x,y:p.y};persistNodePositions();renderGraph();toast("Layout saved in this browser")}
 else selectNode(g.nodeId)
}
function focusNode(id,behavior="smooth"){const canvas=$("#canvas"),node=$("#graph").querySelector(`[data-node="${CSS.escape(id)}"]`);if(!node)return;const c=canvas.getBoundingClientRect(),n=node.getBoundingClientRect();canvas.scrollTo({left:Math.max(0,canvas.scrollLeft+n.left-c.left-(canvas.clientWidth-n.width)/2),top:Math.max(0,canvas.scrollTop+n.top-c.top-(canvas.clientHeight-n.height)/2),behavior})}
function selectNode(id){state.selectedJob=null;state.selectedNode=id;state.selectedEdge=null;renderGraph();renderInspector();requestAnimationFrame(()=>focusNode(id))}
function selectEdge(index){if(!state.flow?.edges[index])return;state.selectedJob=null;state.selectedNode=null;state.selectedEdge=index;renderGraph();renderInspector()}
function renderInspector(){
	 const job=state.selectedJob,flow=state.flow,n=flow?.nodes.find(x=>x.id===state.selectedNode),edge=flow?.edges[state.selectedEdge],mobile=$("#mobileNodeInspector");
	 if(job){const target=job.target||{},terminal=["completed","failed","lost","launch_failed"].includes(job.state),events=job.events||[],ownership=job.owned?"verified live":terminal?"released after terminal":"not verified",output=[jobOutput("stdout",job.last_stdout),jobOutput("stderr",job.last_stderr)].filter(Boolean).join("\n\n"),outputBytes=(job.stdout_size||0)+(job.stderr_size||0);$("#nodeInspector").innerHTML=`<h2>${esc(job.label)}</h2><p class="lede">Durable process evidence on the operator-locked execution backend.</p><span class="risk ${job.state==="completed"?"low":terminal?"high":"active"}">${esc(job.state)}</span><div class="meta-grid"><span class="k">Job id</span><code>${esc(job.job_id)}</code><span class="k">Backend</span><span>${esc(job.backend)} · locked</span><span class="k">Target</span><span>${esc(target.vm||target.container||"configured target")}</span><span class="k">Zone</span><span>${esc(target.zone||"—")}</span><span class="k">Process</span><span>${esc(job.pid||"—")} / workload ${esc(job.workload_pid||"—")}</span><span class="k">Ownership</span><span>${esc(ownership)}</span><span class="k">Exit</span><span>${job.exit_code??"running"}</span><span class="k">Heartbeat</span><span>${job.heartbeat_at?new Date(job.heartbeat_at*1000).toLocaleTimeString():"awaiting"}</span><span class="k">Output bytes</span><span>${job.stdout_size} stdout · ${job.stderr_size} stderr</span><span class="k">Command</span><span>${esc(job.command_preview)}</span><span class="k">Digest</span><code>${esc(short(job.command_sha256,18))}</code></div>${output?`<details><summary>Latest captured output · ${outputBytes} B</summary><pre class="job-output">${esc(output)}</pre></details>`:""}<div class="job-events">${events.slice(-10).reverse().map(e=>`<div class="job-event"><i></i><div><strong>${esc(e.summary)}</strong><span>${esc(e.kind)} · ${new Date(e.ts*1000).toLocaleTimeString()}</span></div></div>`).join("")||'<div class="empty">No job events yet.</div>'}</div>`;mobile.hidden=false;mobile.innerHTML=`<span class="mobile-accent" style="background:var(--blue)"></span><span class="mobile-copy"><strong>${esc(job.label)}</strong><span>${esc(job.state+" · "+job.job_id)}</span></span><button type="button" aria-label="Close job summary">×</button>`;mobile.querySelector("button").onclick=()=>{state.selectedJob=null;renderInspector()};return}
	 if(edge){const source=flow.nodes.find(n=>n.id===edge.source),target=flow.nodes.find(n=>n.id===edge.target),runtime=edgeRuntimeState(edge),runtimeLabel=runtime==="observed"?"Observed transition":runtime==="active"?"Active route":"Not observed in this run";$("#nodeInspector").innerHTML=`<h2>${esc(edgeCaption(edge))}</h2><p class="lede">${esc(source?.label||edge.source)} → ${esc(target?.label||edge.target)}</p><span class="risk ${runtime==="observed"?"low":runtime==="active"?"active":"unknown"}">${esc(runtime==="declared"?"declared":runtime)}</span><div class="meta-grid"><span class="k">Route type</span><span>${edge.loop?"Recovery loop":"Forward route"}</span><span class="k">Source</span><code>${esc(edge.source)}</code><span class="k">Destination</span><code>${esc(edge.target)}</code><span class="k">Condition</span><span>${esc(edge.condition||"Always continue after the source completes")}</span><span class="k">Runtime</span><span>${esc(runtime==="declared"?"Definition view — no run selected":runtimeLabel)}</span></div>`;mobile.hidden=false;mobile.innerHTML=`<span class="mobile-accent" style="background:${edge.loop?"var(--violet)":"var(--blue)"}"></span><span class="mobile-copy"><strong>${esc(edgeCaption(edge))}</strong><span>${esc((source?.label||edge.source)+" → "+(target?.label||edge.target)+" · "+(edge.loop?"recovery loop":"forward route"))}</span></span><button type="button" aria-label="Close edge summary">×</button>`;mobile.querySelector("button").onclick=()=>{state.selectedEdge=null;renderGraph();renderInspector()};return}
 if(!n){$("#nodeInspector").innerHTML='<div class="empty">Select a node or edge to inspect its declaration and latest observed evidence.</div>';mobile.hidden=true;mobile.innerHTML="";return}
 const ag=agentById(n.agent),ev=eventFor(n.id),description=n.description||ag?.description||"Declared graph boundary",eventData=ev&&Object.keys(ev.data||{}).length?`<details><summary>Observed evidence & decision inputs</summary><pre class="event-data">${esc(JSON.stringify(ev.data,null,2))}</pre></details>`:"";
 $("#nodeInspector").innerHTML=`<h2>${esc(n.label)}</h2><p class="lede">${esc(description)}</p>${ev?`<span class="risk ${esc(ev.risk||"low")}">${esc(ev.risk||ev.status)}</span>`:""}<div class="meta-grid"><span class="k">Node id</span><code>${esc(n.id)}</code><span class="k">Type</span><span>${esc(n.type)}</span><span class="k">Identity</span><span>${esc(ag?.label||"system boundary")}</span><span class="k">Model rule</span><span>${esc(ag?.model_selector||"none")}</span>${ev?`<span class="k">Latest event</span><span>${esc(ev.kind)}</span><span class="k">Disposition</span><span>${esc(ev.verdict||ev.status)}</span><span class="k">Summary</span><span>${esc(ev.summary||"—")}</span>`:""}</div><div class="chips">${(n.capabilities||[]).map(c=>`<span class="chip">${esc(c)}</span>`).join("")}</div>${eventData}`;
 mobile.hidden=false;mobile.innerHTML=`<span class="mobile-accent" style="background:${accent[ag?.accent]||accent.slate}"></span><span class="mobile-copy"><strong>${esc(n.label)}</strong><span>${esc(n.type+(ag?" · "+ag.label:"")+(ev?" · "+(ev.summary||ev.kind):""))}</span></span><button type="button" aria-label="Close node summary">×</button>`;mobile.querySelector("button").onclick=()=>{state.selectedNode=null;renderGraph();renderInspector()};
}
function renderFlows(){$("#flowList").innerHTML=state.defs.flows.map(f=>`<button class="flow-card ${state.flow?.id===f.id?"active":""}" data-flow="${esc(f.id)}"><span class="flow-name"><span class="mini-dot running"></span>${esc(f.label)}</span><small>v${f.version} · ${f.nodes.length} nodes · ${f.edges.length} edges</small></button>`).join("");document.querySelectorAll("[data-flow]").forEach(b=>b.onclick=()=>chooseFlow(b.dataset.flow))}
function renderAgents(){const used=new Set(state.flow?.nodes.map(n=>n.agent).filter(Boolean)||[]);$("#agentList").innerHTML=state.defs.agents.filter(a=>used.has(a.id)).map(a=>`<button class="agent-row" data-agent="${esc(a.id)}"><span class="agent-avatar" style="color:${accent[a.accent]||accent.slate}">${esc(a.label.split(/\s/).map(x=>x[0]).join("").slice(0,2))}</span><span><strong>${esc(a.label)}</strong><span>${esc(a.role)}</span></span></button>`).join("");document.querySelectorAll("[data-agent]").forEach(b=>b.onclick=()=>{const n=state.flow.nodes.find(n=>n.agent===b.dataset.agent);if(n)selectNode(n.id)})}
function renderRuns(){const rows=state.runs.filter(r=>r.flow_id===state.flow?.id),visible=rows.slice(0,24),remaining=rows.length-visible.length;$("#runList").innerHTML=rows.length?visible.map(r=>`<button class="run-card ${state.run?.run_id===r.run_id?"active":""}" data-run="${esc(r.run_id)}" ${state.run?.run_id===r.run_id?'aria-current="true"':""}><span class="run-name"><span class="mini-dot ${esc(r.status)}"></span>${esc(short(runTaskLabel(r),34))}</span><small>conversation ${esc(r.session)} · ${esc(runTimestamp(r))}</small></button>`).join("")+(remaining?`<a class="older-runs" href="/history">${remaining} older task run${remaining===1?"":"s"} in History →</a>`:""):'<div class="empty">No task runs exist for this workflow yet.</div>';document.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>chooseRun(b.dataset.run))}
function renderScope(){let rows=state.runs.filter(r=>r.flow_id===state.flow?.id);const picker=$("#runPicker"),selected=state.run?.run_id||"",endeavorLink=$("#endeavorLink"),endeavorMeta=$("#endeavorMeta"),conversationLink=$("#conversationLink"),conversationMeta=$("#conversationMeta"),decisionMeta=$("#decisionMeta");if(state.run?.flow_id===state.flow?.id&&!rows.some(r=>r.run_id===selected))rows=[state.run,...rows];picker.innerHTML='<option value="">Choose a task run…</option>'+rows.map(r=>`<option value="${esc(r.run_id)}" ${selected===r.run_id?"selected":""}>${esc(short(runTaskLabel(r),68))} · ${esc(runTimestamp(r))}</option>`).join("");if(state.run){const endeavor=endeavorFor(state.run),count=Number(endeavor?.conversation_count??1),events=state.run.events?.length||0;if(endeavor?.loading){endeavorLink.textContent="Resolving endeavor…";endeavorLink.href=historyURL(state.run.session);endeavorMeta.textContent="Broader objective container"}else if(endeavor){endeavorLink.textContent=endeavor.endeavor_title||"Untitled endeavor";endeavorLink.href=`/history?endeavor=${encodeURIComponent(endeavor.endeavor_id)}`;endeavorMeta.textContent=`${count} conversation${count===1?"":"s"} · broader objective`}else{endeavorLink.textContent="Single-conversation endeavor";endeavorLink.href=historyURL(state.run.session);endeavorMeta.textContent="No broader grouping recorded"}conversationLink.textContent=runConversationLabel(state.run);conversationLink.href=historyURL(state.run.session);conversationLink.title="Open this conversation inside its endeavor";conversationMeta.textContent=`session ${state.run.session} · one chat thread`;decisionMeta.textContent=`${events} event${events===1?"":"s"} · ${state.run.status}`}else{endeavorLink.textContent="Select a task run first";endeavorLink.href="/history";endeavorMeta.textContent="Broader objective";conversationLink.textContent="No conversation selected";conversationLink.href="/history";conversationLink.removeAttribute("title");conversationMeta.textContent="One chat thread";decisionMeta.textContent="Select a task run"}}
function renderJobs(){const selected=state.selectedJob?.job_id;$("#executionLock").textContent=state.executionLock?.backend?`${state.executionLock.backend.toUpperCase()} locked · agent cannot retarget`:"backend lock unavailable";$("#jobList").innerHTML=state.jobs.length?state.jobs.slice(0,12).map(j=>`<button class="job-card ${selected===j.job_id?"active":""}" data-job="${esc(j.job_id)}"><span class="job-head"><span class="mini-dot ${esc(j.state)}"></span><strong>${esc(j.label)}</strong><span class="risk ${j.state==="completed"?"low":["failed","lost","launch_failed"].includes(j.state)?"high":"active"}">${esc(j.state)}</span></span><small>${esc(j.job_id)} · ${j.stdout_size+j.stderr_size} B</small></button>`).join(""):'<div class="empty">No durable jobs yet.</div>';document.querySelectorAll("[data-job]").forEach(b=>b.onclick=()=>chooseJob(b.dataset.job))}
function renderTrail(){const es=state.run?.events||[];$("#trailMeta").textContent=state.run?`${short(runTaskLabel(state.run),70)} · ${state.run.status} · ${es.length} observed events`:"Choose a task run above to overlay its observed execution.";$("#eventTrail").innerHTML=es.length?es.map((e,i)=>`<button class="event-pill ${i===es.length-1?"current":""}" data-event-node="${esc(e.node_id)}"><b>${esc(e.summary||e.kind)}</b><span>${esc(e.node_id)} · ${new Date(e.ts*1000).toLocaleTimeString()}</span></button>`).join(""):'<div class="empty">This is the reusable workflow definition. Select a task run to see which nodes and routes it actually used.</div>';document.querySelectorAll("[data-event-node]").forEach(b=>b.onclick=()=>selectNode(b.dataset.eventNode))}
function proposalSummary(a){const p=a.proposal||{},v=a.verdict||{};return v.objection||v.reason||(a.assessment?.reasons||[])[0]||p.intended_effect||"This action needs an operator decision."}
function renderActions(){const pending=state.actions.filter(a=>a.status==="human_pending");$("#approvalQueue").innerHTML=pending.length?pending.map(a=>`<article class="approval"><div class="approval-head"><strong>${esc(a.tool_name)}</strong><span class="risk ${esc(a.risk)}">${esc(a.risk)}</span></div><p>${esc(proposalSummary(a))}</p><div class="target">${esc((a.proposal?.targets||[]).join(" · ")||"Target was not resolved")}</div><details><summary>Exact proposal & safeguards</summary><pre>${esc(JSON.stringify({arguments:a.proposal?.arguments,postcondition:a.proposal?.postcondition,invariants:a.proposal?.invariants,rollback:a.proposal?.rollback},null,2))}</pre></details><div class="decision"><button class="deny" data-deny="${esc(a.action_id)}">Block</button><button class="approve" data-approve="${esc(a.action_id)}">Approve once</button></div></article>`).join(""):'<div class="empty">No actions need you.</div>';document.querySelectorAll("[data-approve]").forEach(b=>b.onclick=()=>openDecision(b.dataset.approve,"approve"));document.querySelectorAll("[data-deny]").forEach(b=>b.onclick=()=>openDecision(b.dataset.deny,"deny"))}
function soundnessDecision(decision){return({accept:["Claim supported","low"],fail:["Claim not supported","high"],probe:["Test requested","medium"],continue:["More evidence needed","medium"],completed:["Check completed","low"],pending:["Awaiting evidence","medium"]})[decision]||[String(decision||"Check recorded"),"medium"]}
function renderSoundness(){const all=state.actions.flatMap(a=>(a.soundness_checks||[]).map(c=>({...c,tool_name:a.tool_name,action_session:a.session,action_task:a.task,action_id:a.action_id}))).sort((a,b)=>b.updated_at-a.updated_at),checks=(state.soundnessScope==="selected"?(state.run?all.filter(c=>c.run_id===state.run.run_id):[]):all).slice(0,8),context=$("#soundnessContext");$("#soundnessSelected").classList.toggle("active",state.soundnessScope==="selected");$("#soundnessSelected").setAttribute("aria-pressed",state.soundnessScope==="selected");$("#soundnessAll").classList.toggle("active",state.soundnessScope==="all");$("#soundnessAll").setAttribute("aria-pressed",state.soundnessScope==="all");if(state.soundnessScope==="selected"&&state.run){const endeavor=endeavorFor(state.run);context.innerHTML=`<div class="soundness-context"><strong>${esc(short(runTaskLabel(state.run),46))}</strong><span>${esc(endeavor?.endeavor_title||"single-conversation endeavor")} › conversation ${esc(state.run.session)} › ${esc(state.run.run_id)}</span></div>`}else if(state.soundnessScope==="all")context.innerHTML='<div class="soundness-context"><strong>Cross-run view</strong><span>Each check below names its task run and conversation.</span></div>';else context.innerHTML="";let empty=state.soundnessScope==="selected"&&!state.run?"Choose an observed task run above to see only the checks performed for it.":state.soundnessScope==="selected"?"No independent soundness checks were recorded for this task run.":"No independent checks have been recorded yet.";$("#soundnessQueue").innerHTML=checks.length?checks.map(c=>{const v=Object.keys(c.verdict||{}).length?c.verdict:c.plan||{},decision=v.decision||c.status,[label,risk]=soundnessDecision(decision),run=state.runs.find(r=>r.run_id===c.run_id)||(state.run?.run_id===c.run_id?state.run:null),task=run?runTaskLabel(run):c.action_task||c.run_id,session=run?.session||c.session||c.action_session||"-";return`<article class="soundness-card"><header><strong>${esc(c.tool_name||"action check")}</strong><span class="risk ${risk}">${esc(label)}</span></header><div class="soundness-origin"><b>${esc(short(task,48))}</b><span>conversation ${esc(session)} · ${esc(c.run_id)}</span></div><p>${esc(v.hypothesis||"Testing the declared postcondition")}</p><small>${esc(v.test_description||"Awaiting the independent observation")}</small><details><summary>Test, evidence & interpretation</summary><pre>${esc(JSON.stringify({test:v.test_description,probe:c.plan?.probe,evidence:c.result,interpretation:v.reason},null,2))}</pre></details><button class="soundness-focus" data-soundness-run="${esc(c.run_id)}">View this check in its decision trail →</button><a class="older-runs" href="${historyURL(session)}">Open conversation history ↗</a></article>`}).join(""):`<div class="empty">${esc(empty)}</div>`;document.querySelectorAll("[data-soundness-run]").forEach(b=>b.onclick=()=>chooseSoundnessRun(b.dataset.soundnessRun))}
function openDecision(id,decision){const action=state.actions.find(a=>a.action_id===id);if(!action)return;state.pendingDecision={id,decision};$("#decisionTitle").textContent=decision==="approve"?"Approve this action once?":"Block this action?";$("#decisionReason").textContent=proposalSummary(action);$("#decisionCall").textContent=JSON.stringify({tool:action.tool_name,targets:action.proposal?.targets,arguments:action.proposal?.arguments,postcondition:action.proposal?.postcondition?.description,rollback:action.proposal?.rollback},null,2);$("#decisionNote").value=decision==="approve"?"":"";$("#noteHint").textContent=decision==="deny"?"(recommended)":"(record the verified safeguard)";const confirm=$("#decisionConfirm");confirm.textContent=decision==="approve"?"Approve once":"Block action";confirm.className=decision==="approve"?"confirm-approve":"confirm-deny";$("#decisionDialog").showModal();$("#decisionNote").focus()}
async function submitDecision(){if(!state.pendingDecision)return;const {id,decision}=state.pendingDecision,note=$("#decisionNote").value.trim();if(decision==="approve"&&!note){$("#decisionNote").focus();toast("Record the safeguard that makes this approval sound");return}try{await api(`/admin/actions/${encodeURIComponent(id)}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,note})});$("#decisionDialog").close();state.pendingDecision=null;toast(decision==="approve"?"Action approved for one matching retry":"Action blocked");await refresh()}catch(e){toast(e.message)}}
function syncModeControls(){const definition=state.mode==="definition";$("#definitionMode").classList.toggle("active",definition);$("#definitionMode").setAttribute("aria-pressed",definition);$("#runMode").classList.toggle("active",!definition);$("#runMode").setAttribute("aria-pressed",!definition)}
function chooseFlow(id){state.flow=flowById(id);state.run=null;state.selectedJob=null;state.selectedNode=state.flow.entry;state.selectedEdge=null;state.mode="definition";state.zoom=.82;state.autoFit=false;syncModeControls();$("#canvas").scrollTo({left:0,top:0});renderAll()}
async function chooseRun(id){if(!id){state.run=null;state.mode="definition";syncModeControls();renderAll();return}state.run=await api(`/admin/graphs/runs/${encodeURIComponent(id)}`);state.mode="run";state.flow=flowById(state.run.flow_id);state.soundnessScope="selected";state.selectedJob=null;state.selectedNode=state.run.current_node;state.selectedEdge=null;syncModeControls();renderAll();loadEndeavorContext(state.run);requestAnimationFrame(()=>focusNode(state.selectedNode))}
async function chooseSoundnessRun(id){try{await chooseRun(id);const checker=state.flow?.nodes.find(n=>n.id==="soundness_checker");if(checker)selectNode(checker.id)}catch(e){toast(e.message)}}
async function chooseJob(id){state.selectedJob=await api(`/admin/jobs/${encodeURIComponent(id)}`);state.selectedNode=null;state.selectedEdge=null;renderGraph();renderJobs();renderInspector()}
function renderAll(){if(!state.flow)return;$("#flowTitle").textContent=state.flow.label;$("#flowDescription").textContent=state.flow.description;renderFlows();renderRuns();renderScope();renderJobs();renderAgents();renderGraph();renderTrail();renderInspector();renderActions();renderSoundness()}
async function refresh(){const serial=++state.serial,selectedRunId=state.run?.run_id,selectedJobId=state.selectedJob?.job_id;try{const [defs,runs,actions,jobs]=await Promise.all([state.defs?Promise.resolve(state.defs):api("/admin/graphs"),api("/admin/graphs/runs?limit=60"),api("/admin/actions?limit=100"),api("/admin/jobs?limit=100")]);if(serial!==state.serial)return;state.defs=defs;state.runs=runs.items;state.actions=actions.items;state.jobs=jobs.items;state.executionLock=jobs.execution_lock;if(!state.flow)state.flow=defs.flows[0];if(selectedRunId&&state.run?.run_id===selectedRunId){const match=state.runs.find(r=>r.run_id===selectedRunId);if(match){const observed=await api(`/admin/graphs/runs/${encodeURIComponent(match.run_id)}`);if(state.run?.run_id===selectedRunId)state.run=observed}}if(selectedJobId&&state.selectedJob?.job_id===selectedJobId&&state.jobs.some(j=>j.job_id===selectedJobId)){const observedJob=await api(`/admin/jobs/${encodeURIComponent(selectedJobId)}`);if(state.selectedJob?.job_id===selectedJobId)state.selectedJob=observedJob}renderAll();const waiting=state.actions.filter(a=>a.status==="human_pending").length,running=state.jobs.filter(j=>["launching","running","signaled"].includes(j.state)).length;$(".pulse").classList.toggle("attention",waiting>0);$("#syncState").textContent=waiting?`${waiting} action${waiting===1?"":"s"} need review`:running?`${running} remote job${running===1?"":"s"} active · GCE locked`:`synced ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}`}catch(e){$("#syncState").textContent="control plane unavailable"}}
$("#definitionMode").onclick=()=>chooseRun("");$("#runMode").onclick=()=>{const r=state.runs.find(r=>r.flow_id===state.flow?.id);if(r)chooseRun(r.run_id);else toast("No task run exists for this workflow yet")};$("#runPicker").onchange=e=>chooseRun(e.target.value);$("#soundnessSelected").onclick=()=>{state.soundnessScope="selected";renderSoundness()};$("#soundnessAll").onclick=()=>{state.soundnessScope="all";renderSoundness()};$("#zoomIn").onclick=()=>{state.autoFit=false;state.zoom=Math.min(1.7,state.zoom+.1);renderGraph()};$("#zoomOut").onclick=()=>{state.autoFit=false;state.zoom=Math.max(.22,state.zoom-.1);renderGraph()};$("#fit").onclick=()=>{state.autoFit=true;renderGraph();$("#canvas").scrollTo({left:0,top:0,behavior:"smooth"})};$("#resetLayout").onclick=()=>{if(!state.flow)return;delete state.nodePositions[state.flow.id];persistNodePositions();renderGraph();toast("Node layout reset")};
$("#decisionCancel").onclick=()=>{$("#decisionDialog").close();state.pendingDecision=null};$("#decisionConfirm").onclick=submitDecision;
const graphCanvas=$("#canvas");graphCanvas.onpointerdown=beginCanvasPan;graphCanvas.onpointermove=moveGesture;graphCanvas.onpointerup=e=>finishGesture(e);graphCanvas.onpointercancel=e=>finishGesture(e,true);
let resizeTimer;new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state.flow)renderGraph()},60)}).observe($("#canvas"));
refresh();
// Trace-write-path SSE channel: refresh only when something actually
// happened (debounced); 30s interval is a safety net, not the update path.
let refreshQueued=false;
function queueRefresh(delay=250){if(refreshQueued)return;refreshQueued=true;setTimeout(()=>{refreshQueued=false;refresh()},delay)}
const live=new EventSource("/admin/events/stream");
live.onmessage=()=>queueRefresh();
live.onerror=()=>queueRefresh(2000);
setInterval(refresh,30000);
</script>
</body></html>"""
